name: "PetStore Main"
identifier: "petstoremain"
apiVersion: harness.io/v1
kind: component
type: Location
scope: ACCOUNT
owner: group:account/All_Users
metadata:
  name: petstore-catalog
  description: Petstore application catalog
spec:
  targets:
    - ./systems/petstore-system/catalog-info.yaml
    - ./components/petstore-frontend/catalog-info.yaml
    - ./components/petstore-backend/catalog-info.yaml
    - ./components/petstore-database/catalog-info.yaml
    - ./apis/petstore-api/catalog-info.yaml
    - ./resources/petstore-database-resource/catalog-info.yaml
